#!/bin/bash
# hypr-greeter-wrapper.sh — launched by greetd, generates Hyprland config and execs Hyprland
set -euo pipefail

CONFIG_FILE="/etc/hypr-greeter/config.toml"
TMPDIR=$(mktemp -d /tmp/hypr-greeter.XXXXXXXXXX)

cleanup() {
    rm -rf "$TMPDIR"
}
trap cleanup EXIT

# --- Parse config using Python3 (guaranteed on Arch) ---
# Single Python call writes all extracted values to temp files
python3 - "$CONFIG_FILE" "$TMPDIR" << 'PYEOF'
import tomllib, os, sys
from pathlib import Path

config_path = sys.argv[1]
out_dir = Path(sys.argv[2])

try:
    with open(config_path, 'rb') as f:
        config = tomllib.load(f)
except FileNotFoundError:
    config = {}

# --- Background color ---
colors = config.get('ui', {}).get('colors', {})
bg = colors.get('background', '#1a1b26')
if bg.startswith('#'):
    bg = 'rgb(' + bg[1:] + ')'
(out_dir / 'bg_color').write_text(bg)

# --- Monitor lines ---
monitors = config.get('monitors', [])
login_monitor = ''
monitor_lines = []

if not monitors:
    monitor_lines.append('monitor=,preferred,auto,1')
else:
    for m in monitors:
        name = m.get('name', '')
        res = m.get('resolution', 'preferred')
        pos = m.get('position', 'auto')
        scale = m.get('scale', 1.0)
        monitor_lines.append(f'monitor={name},{res},{pos},{scale}')
        if m.get('login', False) and not login_monitor:
            login_monitor = name

(out_dir / 'monitor_lines').write_text('\n'.join(monitor_lines))
(out_dir / 'login_monitor').write_text(login_monitor)

# --- Keyboard settings ---
input_cfg = config.get('input', {})
kb_lines = []
for key in ('kb_layout', 'kb_variant', 'kb_options'):
    env_key = 'XKB_DEFAULT_' + key.split('_', 1)[1].upper()
    value = (input_cfg.get(key) or os.environ.get(env_key, '')).strip()
    if value:
        kb_lines.append(f'    {key} = {value}')
(out_dir / 'keyboard_settings').write_text('\n'.join(kb_lines))
PYEOF

BG_COLOR=$(cat "$TMPDIR/bg_color")
MONITOR_LINES=$(cat "$TMPDIR/monitor_lines")
LOGIN_MONITOR=$(cat "$TMPDIR/login_monitor")
KEYBOARD_SETTINGS=$(cat "$TMPDIR/keyboard_settings")

# --- Generate Hyprland config ---
HYPRLAND_CONF="$TMPDIR/hyprland.conf"

cat > "$HYPRLAND_CONF" << HYPREOF
# Auto-generated by hypr-greeter-wrapper — do not edit

# Monitors
$MONITOR_LINES

# Minimal appearance
misc {
    disable_hyprland_logo = true
    background_color = $BG_COLOR
}

animations {
    enabled = false
}

decoration {
    blur {
        enabled = false
    }
    shadow {
        enabled = false
    }
    rounding = 0
}

input {
    follow_mouse = 1
    numlock_by_default = true
$KEYBOARD_SETTINGS
}

# Window rules — make the greeter fullscreen on the login monitor
windowrule {
    name = hypr-greeter
    match:class = ^(hypr-greeter)$
    fullscreen = true
    float = false
HYPREOF

# Pin to specific monitor if configured
if [ -n "$LOGIN_MONITOR" ]; then
    cat >> "$HYPRLAND_CONF" << HYPREOF
    monitor = $LOGIN_MONITOR
HYPREOF
fi

cat >> "$HYPRLAND_CONF" << 'HYPREOF'
}

# Launch the greeter TUI in foot terminal
exec-once = foot --app-id=hypr-greeter -e /usr/local/bin/hypr-greeter; hyprctl dispatch exit
HYPREOF

# --- Launch Hyprland ---
exec start-hyprland -- -c "$HYPRLAND_CONF"
