#!/bin/bash
# hypr-greeter-wrapper.sh — launched by greetd, generates Hyprland config and execs Hyprland
set -euo pipefail

CONFIG_FILE="/etc/hypr-greeter/config.toml"
TMPDIR="/tmp/hypr-greeter-$$"

cleanup() {
    rm -rf "$TMPDIR"
}
trap cleanup EXIT

mkdir -p "$TMPDIR"

# --- Parse config using Python3 (guaranteed on Arch) ---
read_config() {
    python3 -c "
import tomllib, json, sys

config_path = '$CONFIG_FILE'
try:
    with open(config_path, 'rb') as f:
        config = tomllib.load(f)
except FileNotFoundError:
    config = {}

# Output as JSON for easy bash consumption
json.dump(config, sys.stdout)
"
}

if [ -f "$CONFIG_FILE" ]; then
    CONFIG_JSON=$(read_config)
else
    CONFIG_JSON='{}'
fi

# Extract background color
BG_COLOR=$(echo "$CONFIG_JSON" | python3 -c "
import json, sys
config = json.load(sys.stdin)
colors = config.get('ui', {}).get('colors', {})
bg = colors.get('background', '#1a1b26')
# Convert hex to Hyprland rgb format: #RRGGBB -> rgb(RRGGBB)
if bg.startswith('#'):
    bg = 'rgb(' + bg[1:] + ')'
print(bg)
")

# Extract monitor configs
MONITOR_LINES=$(echo "$CONFIG_JSON" | python3 -c "
import json, sys
config = json.load(sys.stdin)
monitors = config.get('monitors', [])
login_monitor = None

if not monitors:
    # No monitors configured — auto-detect
    print('monitor=,preferred,auto,1')
else:
    for m in monitors:
        name = m.get('name', '')
        res = m.get('resolution', 'preferred')
        pos = m.get('position', 'auto')
        scale = m.get('scale', 1.0)
        print(f'monitor={name},{res},{pos},{scale}')
        if m.get('login', False) and login_monitor is None:
            login_monitor = name

# Also output the login monitor name on a special line
if login_monitor:
    print(f'# LOGIN_MONITOR={login_monitor}')
")

# Extract keyboard layout settings from config, falling back to XKB_DEFAULT_* env vars
KEYBOARD_SETTINGS=$(echo "$CONFIG_JSON" | python3 -c "
import json, os, sys

config = json.load(sys.stdin)
input_cfg = config.get('input', {})

settings = {
    'kb_layout': input_cfg.get('kb_layout') or os.environ.get('XKB_DEFAULT_LAYOUT', ''),
    'kb_variant': input_cfg.get('kb_variant') or os.environ.get('XKB_DEFAULT_VARIANT', ''),
    'kb_options': input_cfg.get('kb_options') or os.environ.get('XKB_DEFAULT_OPTIONS', ''),
}

for key, value in settings.items():
    value = value.strip()
    if value:
        print(f'    {key} = {value}')
")

# Extract login monitor name from the special comment
LOGIN_MONITOR=$(echo "$MONITOR_LINES" | grep '^# LOGIN_MONITOR=' | sed 's/^# LOGIN_MONITOR=//' || true)
# Filter out the special comment from monitor lines
MONITOR_LINES=$(echo "$MONITOR_LINES" | grep -v '^# LOGIN_MONITOR=' || true)

# --- Generate Hyprland config ---
HYPRLAND_CONF="$TMPDIR/hyprland.conf"

cat > "$HYPRLAND_CONF" << HYPREOF
# Auto-generated by hypr-greeter-wrapper — do not edit

# Monitors
$MONITOR_LINES

# Minimal appearance
misc {
    disable_hyprland_logo = true
    background_color = $BG_COLOR
}

animations {
    enabled = false
}

decoration {
    blur {
        enabled = false
    }
    shadow {
        enabled = false
    }
    rounding = 0
}

input {
    follow_mouse = 1
$KEYBOARD_SETTINGS
}

# Window rules — make the greeter fullscreen on the login monitor
windowrule {
    name = hypr-greeter
    match:class = ^(hypr-greeter)$
    fullscreen = true
    float = false
HYPREOF

# Pin to specific monitor if configured
if [ -n "$LOGIN_MONITOR" ]; then
    cat >> "$HYPRLAND_CONF" << HYPREOF
    monitor = $LOGIN_MONITOR
HYPREOF
fi

cat >> "$HYPRLAND_CONF" << 'HYPREOF'
}

# Launch the greeter TUI in foot terminal
exec-once = foot --app-id=hypr-greeter -e /usr/local/bin/hypr-greeter
HYPREOF

# --- Launch Hyprland ---
exec Hyprland -c "$HYPRLAND_CONF"
