use crate::config::{load_config_from, Config, InputConfig, MonitorConfig};
use std::error::Error;
use std::fmt::Write as _;
use std::os::unix::process::CommandExt;
use std::path::PathBuf;
use std::process::Command;

pub struct BootstrapArgs {
    pub config: Option<PathBuf>,
    pub dry_run: bool,
}

pub fn parse_args(args: &[String]) -> Result<BootstrapArgs, Box<dyn Error>> {
    let mut out = BootstrapArgs { config: None, dry_run: false };
    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--dry-run" => {
                out.dry_run = true;
                i += 1;
            }
            "--config" => {
                i += 1;
                if i >= args.len() {
                    return Err("--config requires a path argument".into());
                }
                out.config = Some(PathBuf::from(&args[i]));
                i += 1;
            }
            other => {
                return Err(format!("unknown bootstrap argument: {}", other).into());
            }
        }
    }
    Ok(out)
}

pub fn run(args: &BootstrapArgs) {
    let cfg = match load_config_from(args.config.as_deref()) {
        Ok(c) => c,
        Err(e) => {
            let path = args
                .config
                .as_deref()
                .map(|p| p.display().to_string())
                .unwrap_or_else(|| "/etc/hypr-greeter/config.toml".to_string());
            eprintln!("hypr-greeter: failed to parse {}: {}", path, e);
            std::process::exit(1);
        }
    };

    let rendered = render_hyprland_conf(&cfg);

    if args.dry_run {
        print!("{}", rendered);
        return;
    }

    let runtime_dir = match std::env::var("XDG_RUNTIME_DIR") {
        Ok(v) if !v.is_empty() => v,
        _ => {
            eprintln!(
                "hypr-greeter: XDG_RUNTIME_DIR not set — check pam_systemd is in /etc/pam.d/greetd"
            );
            std::process::exit(1);
        }
    };

    let dir = PathBuf::from(runtime_dir).join("hypr-greeter");
    if let Err(e) = std::fs::create_dir_all(&dir) {
        eprintln!("hypr-greeter: failed to create {}: {}", dir.display(), e);
        std::process::exit(1);
    }
    let conf_path = dir.join("hyprland.conf");
    if let Err(e) = std::fs::write(&conf_path, rendered.as_bytes()) {
        eprintln!(
            "hypr-greeter: failed to write {}: {}",
            conf_path.display(),
            e
        );
        std::process::exit(1);
    }

    let err = Command::new("start-hyprland")
        .args(["--", "-c"])
        .arg(&conf_path)
        .exec();
    eprintln!("hypr-greeter: exec start-hyprland failed: {}", err);
    std::process::exit(1);
}

pub fn render_hyprland_conf(cfg: &Config) -> String {
    let bg = render_bg_color(&cfg.ui.colors.background);
    let monitor_lines = render_monitor_lines(&cfg.monitors);
    let login_monitor = find_login_monitor(&cfg.monitors);
    let keyboard_settings = render_keyboard_settings(&cfg.input);

    let mut out = String::with_capacity(1024);
    out.push_str("# Auto-generated by hypr-greeter-wrapper — do not edit\n");
    out.push('\n');
    out.push_str("# Monitors\n");
    out.push_str(&monitor_lines);
    out.push('\n');
    out.push('\n');
    out.push_str("# Minimal appearance\n");
    out.push_str("misc {\n");
    out.push_str("    disable_hyprland_logo = true\n");
    writeln!(out, "    background_color = {}", bg).unwrap();
    out.push_str("}\n");
    out.push('\n');
    out.push_str("animations {\n");
    out.push_str("    enabled = false\n");
    out.push_str("}\n");
    out.push('\n');
    out.push_str("decoration {\n");
    out.push_str("    blur {\n");
    out.push_str("        enabled = false\n");
    out.push_str("    }\n");
    out.push_str("    shadow {\n");
    out.push_str("        enabled = false\n");
    out.push_str("    }\n");
    out.push_str("    rounding = 0\n");
    out.push_str("}\n");
    out.push('\n');
    out.push_str("input {\n");
    out.push_str("    follow_mouse = 1\n");
    out.push_str("    numlock_by_default = true\n");
    out.push_str(&keyboard_settings);
    out.push('\n');
    out.push_str("}\n");
    out.push('\n');
    out.push_str("# Window rules — make the greeter fullscreen on the login monitor\n");
    out.push_str("windowrule {\n");
    out.push_str("    name = hypr-greeter\n");
    out.push_str("    match:class = ^(hypr-greeter)$\n");
    out.push_str("    fullscreen = true\n");
    out.push_str("    float = false\n");
    if let Some(m) = login_monitor {
        writeln!(out, "    monitor = {}", sanitize(m)).unwrap();
    }
    out.push_str("}\n");
    out.push('\n');
    out.push_str("# Launch the greeter TUI in foot terminal\n");
    out.push_str("exec-once = foot --app-id=hypr-greeter -e /usr/local/bin/hypr-greeter; hyprctl dispatch exit\n");
    out
}

fn render_bg_color(bg: &str) -> String {
    let bg = sanitize(bg);
    if let Some(rest) = bg.strip_prefix('#') {
        format!("rgb({})", rest)
    } else {
        bg
    }
}

fn sanitize(s: &str) -> String {
    s.replace(['\n', '\r'], "")
}

fn render_monitor_lines(monitors: &[MonitorConfig]) -> String {
    if monitors.is_empty() {
        return String::from("monitor=,preferred,auto,1");
    }
    monitors
        .iter()
        .map(|m| {
            format!(
                "monitor={},{},{},{:?}",
                sanitize(&m.name),
                sanitize(&m.resolution),
                sanitize(&m.position),
                m.scale
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn find_login_monitor(monitors: &[MonitorConfig]) -> Option<&str> {
    monitors.iter().find(|m| m.login).map(|m| m.name.as_str())
}

fn render_keyboard_settings(input_cfg: &InputConfig) -> String {
    let entries = [
        ("kb_layout", "XKB_DEFAULT_LAYOUT", input_cfg.kb_layout.as_str()),
        ("kb_variant", "XKB_DEFAULT_VARIANT", input_cfg.kb_variant.as_str()),
        ("kb_options", "XKB_DEFAULT_OPTIONS", input_cfg.kb_options.as_str()),
    ];
    let mut lines: Vec<String> = Vec::new();
    for (key, env_key, cfg_val) in entries {
        let raw = if cfg_val.is_empty() {
            std::env::var(env_key).unwrap_or_default()
        } else {
            cfg_val.to_string()
        };
        let trimmed = sanitize(raw.trim());
        if !trimmed.is_empty() {
            lines.push(format!("    {} = {}", key, trimmed));
        }
    }
    lines.join("\n")
}
